version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "The Second Son"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "The Seven Son"
workflows:
  bobby-and-sally:
    jobs:
      - bobby
      - sally
